<h1> Hello, Welcome to APSIT's Jenkins CICD PIPELINE TOMCAT SERVER DevOps Demo !! </h1>
<h1> THIS IS THE DEMO OF JENKINS WITH GITHUB AND TOMCAT SERVER </h1>
<h1> THIS APPLICATION IS DEVELOPED BY DIYA </h1>
<h2> TODAYS DATE IS 30 OCT 2025 </h2>
